#ifndef PROCESSMODELVIEWER_GLOBAL_H
#define PROCESSMODELVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSMODELVIEWER_LIBRARY)
#  define PROCESSMODELVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSMODELVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSMODELVIEWER_GLOBAL_H
