#ifndef PROCESSMODEL_GLOBAL_H
#define PROCESSMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSMODEL_LIBRARY)
#  define PROCESSMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSMODEL_GLOBAL_H
